apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
  name: db
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis:ubi8-16.4-3.4-2
  postgresVersion: 16
  postGISVersion: "3.4"
  # service:
  #   type: NodePort
  #   nodePort: 30054
  instances:
  - dataVolumeClaimSpec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
    name: postgres
    replicas: 3
  port: 5432
  postgresVersion: 16
  config:
    parameters:
      shared_preload_libraries: pgvector
  databaseInitSQL:
    key: init-sql
    name: db-pgvector-init
  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          max_connections: "500"
  proxy:
    pgBouncer:
      service:
        type: NodePort
        nodePort: 30054
      replicas: 2
