version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres
    command: postgres -c shared_preload_libraries=vector
    environment:
      POSTGRES_USER: db
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - app_network

volumes:
  postgres_data:
    driver: local
  minio_data:
    driver: local

networks:
  app_network:
    driver: bridge
