name: Build and Push Docker Image & Helm Chart

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ashupednekar535/resumeval
      GHCR_CHART_REPO: ghcr.io/charts
      CHART_PATH: devops/chart

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Extract short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: devops/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.sha_short }}
            ${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.15.2

      - name: Update image tag in manifests.yaml
        run: |
          # Replace repository
          sed -i "s|\(image:\s*\).*|\1${{ env.IMAGE_NAME }}:${{ env.sha_short }}|" \
            ${{ env.CHART_PATH }}/templates/manifests.yaml
          echo "✅ Updated image reference in manifests.yaml"

      - name: Bump Helm chart version (patch)
        run: |
          current_version=$(yq '.version' ${{ env.CHART_PATH }}/Chart.yaml)
          new_version=$(echo $current_version | awk -F. -v OFS=. '{$NF += 1 ; print}')
          yq -i ".version = \"$new_version\"" ${{ env.CHART_PATH }}/Chart.yaml
          echo "Chart version bumped: $current_version → $new_version"

      - name: Helm registry login
        run: echo ${{ secrets.GHCR_PAT }} | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Package Helm chart
        run: |
          helm package ${{ env.CHART_PATH }} --destination ./

      - name: Push Helm chart to GHCR
        run: |
          chart_file=$(ls *.tgz)
          echo "pusing ${chart_file}"
          helm push "$chart_file"  oci://ghcr.io/ashupednekar/charts

      - name: Summary
        run: |
          echo "✅ Docker Image: ${{ env.IMAGE_NAME }}:${{ env.sha_short }}"
          echo "✅ Helm Chart pushed to: oci://${{ env.GHCR_CHART_REPO }}"
